In [1]:
import numpy as np

In [3]:
x = np.array([[1,2,3,4],[5,6,7,8]])
y = np.array([[0.1,0.2,0.3,0.4],[0.5,0.6,0.7,0.8]])

In [4]:
print(x+y)

[[1.1 2.2 3.3 4.4]
 [5.5 6.6 7.7 8.8]]


In [5]:
print(x*y)

[[0.1 0.4 0.9 1.6]
 [2.5 3.6 4.9 6.4]]


(5,)
(1, 5)
(5, 1)
